name: Deploy to Linode Server
on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: rsync-with-ssh-github-actions
        uses: BuildPC/rsync-with-ssh-github-actions@1.0.1
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            host: ${{ secrets.SERVER_IP }}
            port: ${{ secrets.SERVER_PORT }}
            user: ${{ secrets.SERVER_USER }}
            ssh_before: |
              cd /srv/adventurelog.nz/
              sudo -u finn git checkout master
              sudo -u finn git pull origin master
              sudo -u www-data php artisan migrate --addon=finnito.module.places
              sudo -u www-data php artisan cache:clear
              sudo -u www-data php artisan streams:cleanup
              sudo -u www-data php artisan streams:compile
              sudo -u www-data php artisan streams:index
              sudo -u www-data php artisan httpcache:clear
              sudo -u www-data php artisan httpcache:warm
