name: Deploy to Linode Server
on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: rsync-with-ssh-github-actions
        uses: BuildPC/rsync-with-ssh-github-actions@1.0.1
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            host: ${{ secrets.SERVER_IP }}
            port: ${{ secrets.SERVER_PORT }}
            user: ${{ secrets.SERVER_USER }}
            ssh_after: |
              bash deploy.sh
