name: Deploy to Linode Server
on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
              cd /srv/adventurelog.nz/
              bash deploy.sh
